version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mdd-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    networks:
      - mdd-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: mdd-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mdd-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: mdd-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mdd-network

volumes:
  postgres_data:

networks:
  mdd-network:
    driver: bridge